version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: bigdata_postgres
    environment:
      POSTGRES_DB: bigdata_lab1
      POSTGRES_USER: Alice
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U Alice" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
      - ./data:/tmp/data
volumes:
  postgres_data: